version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: docker
    command: ["npm", "run", "start:dev"]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"