version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: docker

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"