# Stage 1: Build the application
FROM node:21 as builder
WORKDIR /app
COPY . /app
RUN npm ci
RUN npm run build


# Stage 2: Production image
FROM node:21
WORKDIR /app
COPY package*.json ./
COPY .env* ./
COPY swagger-config.yaml ./
RUN NODE_ENV=production npm ci
COPY --from=builder /app/dist/ dist/
EXPOSE 3000
CMD ["node", "dist/main.js"]
